export const words = [
    "about", "above", "abuse", "actor", "admit", "adult", "after", "again", "agree", "album", "alive", "alone", "along", "amend", "anger", "apply", "argue", "arise", "arrow", "asset", "awake", "award", "adopt", "alarm", "alert", "allow", "aside",
    "basic", "beach", "begin", "being", "below", "beset", "blind", "block", "blood", "bread", "bring", "brown", "build", "bacon", "basin", "batch", "berry", "blast", "brave", "brick", "brush",
    "carry", "chase", "child", "claim", "clean", "clear", "close", "count", "cover", "cross", "chain", "charm", "cheer", "chief", "cliff", "crush",
    "dance", "death", "debut", "delay", "drama", "dream", "drink", "drive", "depth", "dozen",
    "early", "earth", "enemy", "enjoy", "enter", "equal", "event", "every", "exact", "exist", "extra", "eagle", "elbow", "evoke",
    "false", "fight", "final", "focus", "force", "fresh", "front", "fruit", "fault", "feast", "fence", "fever", "flood", "flock", "flour", "fuzzy",
    "grant", "guide", "guilt", "ghost", "gleam", "globe", "goose", "grasp", "greet", "guest",
    "heart", "honor", "human", "haste", "hinge", "humor",
    "issue", 
    "joint", "judge", 
    "kneel",
    "learn", "leave", "level", "limit", "label", "laugh", "layer", "legal", "light", "lower",
    "major", "money", "month", "moral", "music", "match", "medal", "metal", "meter", "mimic", "motor",
    "never", "night", "north", "nurse",
    "offer", "order", 
    "party", "peace", "phone", "place", "plant", "price", "pride", "proof", "prove", "patch", "pearl", "photo", "plain", "plant", "plead", "porch", "press", "proof",
    "quiet", "quick",
    "reach", "ready", "rebel", "right", "river", "round", "ratio", "razor", "rebel", "ridge", "rival", "route", "royal", 
    "scale", "serve", "share", "shift", "short", "smile", "solve", "speak", "speed", "start", "state", "steal", "still", "storm", "study", "style", "scope", "scrap", "shake", "sheep", "shoot", "skate", "slice", "slope", "smart", "snack", "sneak", "solar", "spice", "spoil", "sport", "stack", "stage", "stall", "stone", "strip", "stump", "swirl",
    "teach", "thank", "their", "there", "these", "thick", "think", "throw", "total", "touch", "trade", "train", "treat", "trust", "table", "tease", "tiger", "towel", "trial", "trick", "troop",
    "under", "unity", "unity", "upper", "upset", "utter",
    "value", "visit", "voice", "vowel",
    "waste", "watch", "water", "weigh", "wheel", "where", "white", "whole", "worse", "write", "wrong", "waste", "whisk", "whole", "widen", "world",
    "young", "yield"
];